export default {
  SPLASHSCREEN: 'Splash',
  ONBOARDINGSCREEN: 'onboarding',
  SIGNUPSCREEN: 'Signup',
  LOGINSCREEN: 'Login',
  COMPLETEPROFILESCREEN: 'CompleteProfile',
  BOTTOMTABSSCREEN: 'BottomTabs',
  HELPCENTER: 'HelpCenter',
  BOTTOMTABS: 'BottomTabs',
  CONTRACTORLIST: 'ContractorList',
  MYBOOKMARKS: 'MyBookMarks',
  LOGIN: 'Login',
  MORESERVICES: 'MoreServices',
  UPDATEPROFILE: 'UpdateProfile',
  CONTRACTORPROFILE: 'ContractorProfile',
  PAYMENTS: 'Payments',
  SECURITY: 'Security',
  PRIVACY: 'Privscy',
  INVITEFREIND: 'InviteFriend',
  CONTRACTORDETAILS : 'WorkDetails'
};
