export const units = [
    { id: 32, english: 'Hour', hindi: 'घंटा' },
    { id: 33, english: 'Day', hindi: 'दिन' },
    { id: 34, english: 'Week', hindi: 'सप्ताह' },
    { id: 35, english: 'Month', hindi: 'महीना' },
    { id: 1, english: 'Meter', hindi: 'मीटर' },
    { id: 2, english: 'Centimeter', hindi: 'सेंटीमीटर' },
    { id: 3, english: 'Millimeter', hindi: 'मिलीमीटर' },
    { id: 4, english: 'Kilometer', hindi: 'किलोमीटर' },
    { id: 5, english: 'Foot', hindi: 'फुट' },
    { id: 6, english: 'Inch', hindi: 'इंच' },
    { id: 7, english: 'Square Meter', hindi: 'वर्ग मीटर' },
    { id: 8, english: 'Square Foot', hindi: 'वर्ग फुट' },
    { id: 9, english: 'Cubic Meter', hindi: 'घन मीटर' },
    { id: 10, english: 'Cubic Foot', hindi: 'घन फुट' },
    { id: 11, english: 'Liter', hindi: 'लीटर' },
    { id: 12, english: 'Milliliter', hindi: 'मिलीलीटर' },
    { id: 13, english: 'Gallon', hindi: 'गैलन' },
    { id: 14, english: 'Kilogram', hindi: 'किलोग्राम' },
    { id: 15, english: 'Gram', hindi: 'ग्राम' },
    { id: 16, english: 'Ton', hindi: 'टन' },
    { id: 17, english: 'Square Yard', hindi: 'वर्ग गज' },
    { id: 18, english: 'Square Inch', hindi: 'वर्ग इंच' },
    { id: 19, english: 'Cubic Yard', hindi: 'घन गज' },
    { id: 20, english: 'Cubic Inch', hindi: 'घन इंच' },
    { id: 21, english: 'Pound', hindi: 'पाउंड' },
    { id: 22, english: 'Ounce', hindi: 'औंस' },
    { id: 23, english: 'Barrel', hindi: 'बैरल' },
    { id: 24, english: 'Quart', hindi: 'क्वार्ट' },
    { id: 25, english: 'Pint', hindi: 'पिंट' },
    { id: 26, english: 'Yard', hindi: 'गज' },
    { id: 27, english: 'Micron', hindi: 'माइक्रोन' },
    { id: 28, english: 'Nanometer', hindi: 'नैनोमीटर' },
    { id: 29, english: 'Decimeter', hindi: 'डेसीमीटर' },
    { id: 30, english: 'Hectare', hindi: 'हेक्टेयर' },
    { id: 31, english: 'Acre', hindi: 'एकड़' },

];


